### ISSUE TITLE
Consistent panic when parsing file

### ISSUE THREAD

**Issue by glacials** [LiveSplit/livesplit-core#305]
Running livesplit-core inside an Ubuntu-based Docker container for Splits.io, we're consistently getting the following panic when parsing this file:
```json
{"category":{"longname":"I am The BEST","shortname":"I am The BEST"},"schemaVersion":"v1.0.1","segments":[{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"1","endedAt":{"gametimeMS":0,"realtimeMS":15062}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"2","endedAt":{"gametimeMS":0,"realtimeMS":30092}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"3","endedAt":{"gametimeMS":0,"realtimeMS":44040}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"4","endedAt":{"gametimeMS":0,"realtimeMS":67042}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"5","endedAt":{"gametimeMS":0,"realtimeMS":85091}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"6","endedAt":{"gametimeMS":0,"realtimeMS":116073}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"7","endedAt":{"gametimeMS":0,"realtimeMS":130014}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"8","endedAt":{"gametimeMS":0,"realtimeMS":164027}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"9","endedAt":{"gametimeMS":0,"realtimeMS":237043}},{"bestDuration":{"gametimeMS":0,"realtimeMS":0},"isSkipped":false,"histories":[],"name":"10","endedAt":{"gametimeMS":0,"realtimeMS":240084}}],"game":{"longname":"Stepfish Any%","shortname":"Stepfish Any%"},"links":{},"attempts":{"total":0,"histories":[]},"timer":{"website":"https:\/\/github.com\/glacials\/splits-io\/tree\/master\/public\/schema","shortname":"exchange","longname":"Splits.io Echange Format","version":""}}
```
(haven't tested if it's relevant, but notice the `Echange` typo and the blank timer version)
```
worker_1     | thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/slice/mod.rs:2539:10
worker_1     | stack backtrace:
worker_1     |    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
worker_1     |              at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
worker_1     |    1: std::panicking::default_hook::{{closure}}
worker_1     |              at src/libstd/sys_common/backtrace.rs:70
worker_1     |              at src/libstd/sys_common/backtrace.rs:58
worker_1     |              at src/libstd/panicking.rs:200
worker_1     |    2: std::panicking::rust_panic_with_hook
worker_1     |              at src/libstd/panicking.rs:215
worker_1     |              at src/libstd/panicking.rs:478
worker_1     |    3: std::panicking::continue_panic_fmt
worker_1     |              at src/libstd/panicking.rs:385
worker_1     |    4: rust_begin_unwind
worker_1     |              at src/libstd/panicking.rs:312
worker_1     |    5: core::panicking::panic_fmt
worker_1     |              at src/libcore/panicking.rs:85
worker_1     |    6: core::panicking::panic_bounds_check
worker_1     |              at src/libcore/panicking.rs:61
worker_1     |    7: Run_segment
worker_1     |    8: ffi_call_unix64
worker_1     |    9: ffi_call
worker_1     |   10: rbffi_CallFunction
worker_1     |              at /bundle/ruby/2.7.0/gems/ffi-1.11.3/ext/ffi_c/Call.c:412
worker_1     |   11: custom_trampoline
worker_1     |              at /bundle/ruby/2.7.0/gems/ffi-1.11.3/ext/ffi_c/MethodHandle.c:232
worker_1     |   12: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   13: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   14: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:801
worker_1     |   15: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1929
worker_1     |   16: rb_yield_values2
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1179
worker_1     |              at /usr/src/ruby/vm_eval.c:1227
worker_1     |              at /usr/src/ruby/vm_eval.c:1273
worker_1     |   17: rb_ensure
worker_1     |              at /usr/src/ruby/eval.c:1128
worker_1     |   18: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   19: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   20: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   21: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   22: yield_under
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1171
worker_1     |              at /usr/src/ruby/vm_eval.c:1877
worker_1     |   23: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   24: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   25: vm_call_opt_send
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2661
worker_1     |   26: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   27: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   28: yield_under
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1171
worker_1     |              at /usr/src/ruby/vm_eval.c:1877
worker_1     |   29: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   30: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   31: vm_call_opt_send
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2661
worker_1     |   32: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   33: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   34: yield_under
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1171
worker_1     |              at /usr/src/ruby/vm_eval.c:1877
worker_1     |   35: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   36: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   37: vm_call_opt_send
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2661
worker_1     |   38: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   39: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   40: yield_under
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1171
worker_1     |              at /usr/src/ruby/vm_eval.c:1877
worker_1     |   41: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   42: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   43: vm_call_opt_send
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2661
worker_1     |   44: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   45: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   46: yield_under
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1171
worker_1     |              at /usr/src/ruby/vm_eval.c:1877
worker_1     |   47: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   48: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   49: vm_call_opt_send
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2661
worker_1     |   50: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   51: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   52: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1929
worker_1     |   53: rb_yield_1
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1179
worker_1     |              at /usr/src/ruby/vm_eval.c:1227
worker_1     |              at /usr/src/ruby/vm_eval.c:1233
worker_1     |   54: int_dotimes
worker_1     |              at /usr/src/ruby/numeric.c:5201
worker_1     |   55: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   56: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   57: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   58: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   59: loop_i
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1179
worker_1     |              at /usr/src/ruby/vm_eval.c:1227
worker_1     |              at /usr/src/ruby/vm_eval.c:1330
worker_1     |   60: rb_vrescue2
worker_1     |              at /usr/src/ruby/eval.c:989
worker_1     |   61: rb_rescue2
worker_1     |              at /usr/src/ruby/eval.c:966
worker_1     |   62: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   63: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   64: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   65: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   66: rb_yield
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1179
worker_1     |              at /usr/src/ruby/vm_eval.c:1227
worker_1     |              at /usr/src/ruby/vm_eval.c:1233
worker_1     |              at /usr/src/ruby/vm_eval.c:1243
worker_1     |   67: rb_ary_each
worker_1     |              at /usr/src/ruby/array.c:2135
worker_1     |   68: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   69: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   70: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   71: rb_yield_values2
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1179
worker_1     |              at /usr/src/ruby/vm_eval.c:1227
worker_1     |              at /usr/src/ruby/vm_eval.c:1273
worker_1     |   72: rb_ensure
worker_1     |              at /usr/src/ruby/eval.c:1128
worker_1     |   73: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   74: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   75: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   76: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1929
worker_1     |   77: rb_yield
worker_1     |              at /usr/src/ruby/vm.c:1044
worker_1     |              at /usr/src/ruby/vm.c:1116
worker_1     |              at /usr/src/ruby/vm.c:1134
worker_1     |              at /usr/src/ruby/vm.c:1179
worker_1     |              at /usr/src/ruby/vm_eval.c:1227
worker_1     |              at /usr/src/ruby/vm_eval.c:1233
worker_1     |              at /usr/src/ruby/vm_eval.c:1243
worker_1     |   78: rb_ary_each
worker_1     |              at /usr/src/ruby/array.c:2135
worker_1     |   79: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   80: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   81: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:782
worker_1     |   82: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1929
worker_1     |   83: rb_f_load
worker_1     |              at /usr/src/ruby/load.c:585
worker_1     |              at /usr/src/ruby/load.c:643
worker_1     |              at /usr/src/ruby/load.c:701
worker_1     |   84: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   85: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   86: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:801
worker_1     |   87: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   88: rb_f_load
worker_1     |              at /usr/src/ruby/load.c:585
worker_1     |              at /usr/src/ruby/load.c:643
worker_1     |              at /usr/src/ruby/load.c:701
worker_1     |   89: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   90: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   91: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:801
worker_1     |   92: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1929
worker_1     |   93: rb_f_load
worker_1     |              at /usr/src/ruby/load.c:585
worker_1     |              at /usr/src/ruby/load.c:643
worker_1     |              at /usr/src/ruby/load.c:701
worker_1     |   94: vm_call_cfunc
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2514
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:2539
worker_1     |   95: vm_call_method
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:3053
worker_1     |   96: vm_exec_core
worker_1     |              at /usr/src/ruby/vm_insnhelper.c:4023
worker_1     |              at /usr/src/ruby/insns.def:801
worker_1     |   97: rb_vm_exec
worker_1     |              at /usr/src/ruby/vm.c:1920
worker_1     |   98: rb_ec_exec_node
worker_1     |              at /usr/src/ruby/eval.c:277
worker_1     |   99: ruby_run_node
worker_1     |              at /usr/src/ruby/eval.c:335
```

**Comment by CryZe** [comment]
This seems to get parsed as a run with 0 segments (I haven‘t tried it yet, but it seems very likely), which would then result in an indexing attempt of the last segment by you guys with len - 1 being -1 (and it being unsigned underflowing to max uint) in the following line:

https://github.com/glacials/splits-io/blob/f3cd4b090e9d6d20c3e06fd73bd5646047714772/app/models/concerns/unparsed_run.rb#L134

```ruby
      # Set run duration
      last_seg = run.segment(run.len - 1)
      run_data[:realtime_duration_ms] = last_seg.personal_best_split_time.real_time&.total_seconds&.*(1000) || 0
      run_data[:gametime_duration_ms] = last_seg.personal_best_split_time.game_time&.total_seconds&.*(1000) || 0
```

**Comment by glacials** [comment]
Ah okay gotcha, thanks for investigating that! Is a panic and crash expected behavior for programmer error like this then? It was surprising at the time to even discover our worker had crashed, as crashing isn't something we've had to deal with in Ruby land much. If so I'll know to start putting process-level safeguards on our worker.

**Comment by CryZe** [comment]
Panics usually indicate actual bugs and are usually unexpected and should be fixed. So in general livesplit-core doesn't panic for unexpected splits for example (which it didn't here either), as those are expected to be faulty. Only for misuse we panic. In general panics can be caught like exceptions in Rust. But at the moment this isn't allowed across a C API boundary in Rust. There's an effort to standardize defining the behavior there. Then Ruby should easily be able to catch the exception. However at least C# is already able to catch these exceptions it seems (Rust throws a SIGILL signal and C# recovers from it), so Ruby might already be able to do so as well.

**Comment by glacials** [comment]
Cool, thanks! I'll do some light testing and keep an eye on that project. 🤞

**Comment by wooferzfg** [comment]
Should the parser allow a splits file to be parsed with no segments? We don't ever allow a run with no segments in LSO.

**Comment by CryZe** [comment]
Well so far the idea is that `Run` can freely have as many segments as it wants, but the `Timer` validates that there's at least one segment and fails creation when that's not the case.

https://docs.rs/livesplit-core/0.11.0/livesplit_core/timing/struct.Timer.html#method.new

**Comment by wooferzfg** [comment]
That makes sense. The most reasonable fix would be for Splits.io to verify that the parsed run has at least one segment then.

**Comment by CryZe** [comment]
Yeah that's what they did: https://github.com/glacials/splits-io/commit/2c6a7cf229bf9615b40d03716bd53718e4e3c268

**Comment by CryZe** [comment]
So I guess this can be closed then.
